# Pembersihan Data Steam Review Game

Notebook ini digunakan untuk membersihkan dataset `steam_review_game.csv` agar hanya menyisakan kolom yang diperlukan (`appid`, `review`, `name`) dan menghapus data-data yang tidak valid.

**Langkah-langkah:**
1. Import library & load data
2. Lihat info awal dataset
3. Hapus kolom yang tidak diperlukan
4. Hapus missing values pada kolom appid, review, dan name
5. Bersihkan whitespace pada kolom review dan name
6. Hapus review yang kosong (empty string / whitespace only)
7. Hapus duplikat berdasarkan kolom review
8. Lihat info dataset setelah dibersihkan
9. Simpan ke file CSV baru

In [1]:
# Import library yang diperlukan dan load dataset
import pandas as pd

df = pd.read_csv('steam_review_game.csv')
print(f'Dataset berhasil dimuat!')
print(f'Jumlah baris: {len(df):,}')
print(f'Jumlah kolom: {len(df.columns)}')
print(f'Kolom: {list(df.columns)}')

Dataset berhasil dimuat!
Jumlah baris: 730,945
Jumlah kolom: 11
Kolom: ['appid', 'review', 'word_count', 'voted_up', 'votes_up', 'votes_funny', 'timestamp_created', 'author_playtime_forever', 'name', 'price', 'release_date']

In [2]:
# Kode ini untuk menampilkan info awal dataset sebelum dibersihkan
print('=== INFO AWAL DATASET ===')
print(f'Shape: {df.shape}')
print(f'\nMissing values per kolom:')
print(df.isnull().sum())
print(f'\nSample data (5 baris pertama):')
df.head()

=== INFO AWAL DATASET ===
Shape: (730945, 11)

Missing values per kolom:
appid                           0
review                          0
word_count                      0
voted_up                        0
votes_up                        0
votes_funny                     0
timestamp_created               0
author_playtime_forever         0
name                            0
price                           0
release_date               730945
dtype: int64

Sample data (5 baris pertama):

,appid,review,word_count,voted_up,votes_up,votes_funny,timestamp_created,author_playtime_forever,name,price,release_date
0,1938090,I really loved the game but itll take you a lo...,26,True,0,0,1757864825,1485,Call of Duty: Modern Warfare II,6999,NaN
1,1938090,i cant join the game for some reason,8,False,0,0,1757864289,346,Call of Duty: Modern Warfare II,6999,NaN
2,1938090,these new games are just living in the MASSIVE...,133,False,0,0,1757861908,2131,Call of Duty: Modern Warfare II,6999,NaN
3,1938090,Its fun of course you have cheaters but beside...,25,True,0,0,1757854957,344,Call of Duty: Modern Warfare II,6999,NaN
4,1938090,I play this game as a casual player on PC. I h...,39,False,0,1,1757846859,1746,Call of Duty: Modern Warfare II,6999,NaN

In [3]:
# Kode ini untuk menghapus kolom yang tidak diperlukan
# Hanya menyisakan kolom: appid, review, name
kolom_dihapus = [col for col in df.columns if col not in ['appid', 'review', 'name']]
print(f'Kolom yang akan dihapus: {kolom_dihapus}')

df = df[['appid', 'review', 'name']]

print(f'\nKolom yang tersisa: {list(df.columns)}')
print(f'Shape setelah hapus kolom: {df.shape}')

Kolom yang akan dihapus: ['word_count', 'voted_up', 'votes_up', 'votes_funny', 'timestamp_created', 'author_playtime_forever', 'price', 'release_date']

Kolom yang tersisa: ['appid', 'review', 'name']
Shape setelah hapus kolom: (730945, 3)

In [4]:
# Kode ini untuk menghapus baris yang memiliki missing value (NaN/null)
# pada kolom appid, review, atau name
jumlah_sebelum = len(df)

print('Missing values sebelum dihapus:')
print(df.isnull().sum())

df = df.dropna(subset=['appid', 'review', 'name'])

jumlah_sesudah = len(df)
print(f'\nBaris dihapus karena missing value: {jumlah_sebelum - jumlah_sesudah:,}')
print(f'Sisa baris: {jumlah_sesudah:,}')

Missing values sebelum dihapus:

appid     0
review    0
name      0
dtype: int64

Baris dihapus karena missing value: 0
Sisa baris: 730,945

In [5]:
# Kode ini untuk membersihkan whitespace (spasi berlebih) di kolom review dan name
# Strip leading/trailing whitespace
df['review'] = df['review'].astype(str).str.strip()
df['name'] = df['name'].astype(str).str.strip()

print('Whitespace pada kolom review dan name sudah dibersihkan.')

Whitespace pada kolom review dan name sudah dibersihkan.

In [6]:
# Kode ini untuk menghapus baris yang reviewnya kosong (empty string)
# setelah di-strip whitespace-nya
jumlah_sebelum = len(df)

df = df[df['review'] != '']

jumlah_sesudah = len(df)
print(f'Baris dihapus karena review kosong: {jumlah_sebelum - jumlah_sesudah:,}')
print(f'Sisa baris: {jumlah_sesudah:,}')

Baris dihapus karena review kosong: 0
Sisa baris: 730,945

In [7]:
# Kode ini untuk menghapus duplikat berdasarkan kolom review
# Catatan: appid dan name TIDAK dijadikan basis duplikat, karena
# satu game bisa punya banyak review (appid & name pasti duplikat)
# Yang dihapus hanya jika teks review-nya persis sama
jumlah_sebelum = len(df)

df = df.drop_duplicates(subset=['review'], keep='first')

jumlah_sesudah = len(df)
print(f'Baris dihapus karena review duplikat: {jumlah_sebelum - jumlah_sesudah:,}')
print(f'Sisa baris: {jumlah_sesudah:,}')

Baris dihapus karena review duplikat: 9,999
Sisa baris: 720,946

In [8]:
# Kode ini untuk reset index setelah semua pembersihan
df = df.reset_index(drop=True)

print('Index sudah di-reset.')
print(f'Shape final: {df.shape}')

Index sudah di-reset.
Shape final: (720946, 3)

In [9]:
# Kode ini untuk menampilkan info dataset setelah dibersihkan
print('=== INFO DATASET SETELAH DIBERSIHKAN ===')
print(f'Jumlah baris: {len(df):,}')
print(f'Jumlah kolom: {len(df.columns)}')
print(f'Kolom: {list(df.columns)}')
print(f'\nMissing values:')
print(df.isnull().sum())
print(f'\nDuplikat review: {df.duplicated(subset=["review"]).sum()}')
print(f'\nSample data (5 baris pertama):')
df.head()

=== INFO DATASET SETELAH DIBERSIHKAN ===
Jumlah baris: 720,946
Jumlah kolom: 3
Kolom: ['appid', 'review', 'name']

Missing values:
appid     0
review    0
name      0
dtype: int64

Duplikat review: 0

Sample data (5 baris pertama):

,appid,review,name
0,1938090,I really loved the game but itll take you a lo...,Call of Duty: Modern Warfare II
1,1938090,i cant join the game for some reason,Call of Duty: Modern Warfare II
2,1938090,these new games are just living in the MASSIVE...,Call of Duty: Modern Warfare II
3,1938090,Its fun of course you have cheaters but beside...,Call of Duty: Modern Warfare II
4,1938090,I play this game as a casual player on PC. I h...,Call of Duty: Modern Warfare II

In [10]:
# Kode ini untuk menyimpan dataset yang sudah bersih ke file CSV baru
df.to_csv('steam_review_game_bersih.csv', index=False)

print(f'Dataset bersih berhasil disimpan ke: steam_review_game_bersih.csv')
print(f'Total baris yang tersimpan: {len(df):,}')

Dataset bersih berhasil disimpan ke: steam_review_game_bersih.csv
Total baris yang tersimpan: 720,946